// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSqrvrzdhqpLvaMCHhWKCDxvZIkLRlSvk',
    appId: '1:317607047223:web:f5044488e3a8dfe4b28fb2',
    messagingSenderId: '317607047223',
    projectId: 'vehicles-3e91b',
    authDomain: 'vehicles-3e91b.firebaseapp.com',
    storageBucket: 'vehicles-3e91b.appspot.com',
    measurementId: 'G-RCPYDTTP7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_sgii2d9ms-zxCG_XZhtZz3SrGMCIqs4',
    appId: '1:317607047223:android:6cb50e79b039364eb28fb2',
    messagingSenderId: '317607047223',
    projectId: 'vehicles-3e91b',
    storageBucket: 'vehicles-3e91b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBblwVM0KWNVW4rsdz0zWv__-OCLpYsrGk',
    appId: '1:317607047223:ios:443cbdd0e420afbab28fb2',
    messagingSenderId: '317607047223',
    projectId: 'vehicles-3e91b',
    storageBucket: 'vehicles-3e91b.appspot.com',
    iosClientId: '317607047223-duqc1lmdpc6s5hlanl63ldl7fnr53skj.apps.googleusercontent.com',
    iosBundleId: 'com.example.vehicles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBblwVM0KWNVW4rsdz0zWv__-OCLpYsrGk',
    appId: '1:317607047223:ios:0314d4a3c08faedcb28fb2',
    messagingSenderId: '317607047223',
    projectId: 'vehicles-3e91b',
    storageBucket: 'vehicles-3e91b.appspot.com',
    iosClientId: '317607047223-jum1hqoirj5k4aivmfjf2ri8ld8m8ujg.apps.googleusercontent.com',
    iosBundleId: 'com.example.vehicles.RunnerTests',
  );
}
